config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"
  resources :treats, only: %i[index new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/treat.rb
class Treat < ApplicationRecord
  before_validation :set_nameless_user
  before_save :set_treat

  validates :user, presence: true, length: {maximum: 30}
  validates :event, presence: true, length: {maximum: 30}
  validates :tired_level, presence:true, inclusion: { in: 1..3 }
  validates :reward_category, presence: true, length: {maximum: 30}

  private
  def set_nameless_user
    #セッターメソッドを呼ぶときにはselfを省略できない、らしい。うーん。
    self.user = "名無し" if user.blank?
  end

  def set_treat
      treat_results = {
        "ごちそう" => {
            1 => [
                "コンビニで好きなスイーツを購入",
                "コンビニで好きなお菓子を購入",
                "コンビニで好きなアイスを購入",
                "パン屋さんで素敵なパンを購入",
                "スタバでフラペチーノを堪能",
                "スーパーで贅沢にお刺身を購入",
                "スーパーで特売のステーキを購入",
              ],
              2 => [
                "近所のケーキ屋さんで好きなケーキ購入",
                "吉野家でうな丼に舌鼓",
                "松屋でごろごろチキンカレーを満喫",
                "Uber Eatrsでお好きな料理をオーダー",
                "お寿司屋さんで贅沢ランチ",
                "お蕎麦屋さんで贅沢ランチ",
                "いきなりステーキでお肉を満喫",
                "インドカレー屋で刺激的なランチを堪能",
                "宅配ピザでピザパーティー",
                "近所の美味しいラーメンを満喫",
                "近所のカフェで身も心もリフレッシュ",
                "デパ地下で惣菜を好きなだけ購入"
              ],
              3 => [
                "Uber Eatrsで好きなものを頼み放題",
                "お寿司屋さんで贅沢ディナー",
                "お蕎麦屋さんで贅沢ディナー",
                "家族と焼き肉屋さんで贅沢ディナー",
                "食べログ百名店で舌鼓",
                "ポケットコンシェルジュで素敵なお店を予約",
                "大切な人とイタリアンでコース料理を堪能",
              ]
            },
            "ショッピング" => {
              1 => [
                "100円ショップで爆買",
                "3coinsで爆買",
                "ファストファッションでショッピング",
                "ドン・キホーテでショッピング",
                "本屋さんで気になる本を購入",
                "Amazonでショッピング(2000円以下)",
                "雑貨屋さんで気ままにショッピング"
              ],
              2 => [
                "無印良品で素敵なショッピング",
                "ikeaで気ままにショッピング",
                "ニトリで楽しくショッピング",
                "セレクトショップでオシャレにショッピング",
                "家電量販店で楽しくショッピング",
                "Amazonでショッピング(1万円以下)",
                "@cosmeで気になるコスメをショッピング",
                "アンテナショップで気ままにショッピング",
                "LUMINEでお得にショッピング",
                "PARCOで楽しくショッピング",
                "東急ハンズで心踊らすショッピング"
              ],
              3 => [
                "Amazonで注文確定し放題",
                "LOUIS VUITTONでエレガントにショッピング",
                "IPSAで心ときめくショッピング",
                "大塚家具で豪華にショッピング",
                "伊勢丹でお上品にお買い物",
                "本屋で漫画全巻大人買い"
              ]
            },
            "エンタメ" => {
              1 => [
                "YouTubeで癒やしのネコ動画を視聴",
                "好きなアーティストの曲を満喫",
                "Netflixで好きなドラマを視聴",
                "radikoで深夜ラジオのアーカイブを視聴",
                "録画していたバレエティ番組を視聴",
                "気になっていたスマホゲームをダウンロード"
               ],
              2 => [
                "Youtubeで好きなだけ見放題",
                "Netflixで好きなドラマを1シーズン視聴",
                "Netflixで好きなアニメを全話一気観",
                "映画館で映画を堪能",
                "カラオケでストレス発散",
                "ボーリングでエキサイティング",
                "好きなゲームを1時間プレイ"
              ],
              3 => [
                "好きなアーティストのライブに参戦",
                "好きなアイドルのイベントに参戦",
                "音楽フェスを堪能",
                "好きなお笑い芸人の単独ライブで爆笑",
                "好きなサッカーチームの試合を観戦",
                "好きな野球チームの試合を観戦",
                "好きなゲームを気が済むまでプレイ",
                "ボードゲームカフェで1日満喫"
              ]
            }
          }
          #nameカラムにはこの戻り値が入る。だからDBカラムにあってもビューでユーザーからの入力値にreward_nameは必要ない
          self.reward_name = treat_results.dig(reward_category, tired_level).sample
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def top ; end 
end

app/controllers/treats_controller.rb
class TreatsController < ApplicationController
  def index
    @treats = Treat.all.order(created_at: :desc).page(params[:page])
  end

  def new
    @treat = Treat.new
  end

  def create
    @treat = Treat.new(treat_params)
    if @treat.save
      redirect_to @treat
    else
      render :new
    end
  end

  def show
    @treat = Treat.find(params[:id])
  end

  private

  def treat_params
    params.require(:treat).permit(:user, :event, :tired_level, :reward_category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/treats_helper.rb
module TreatsHelper
end

app/views/home/top.html.slim
.text-center.top-message 
  h1 今日も一日いろいろありましたね
  p 
    | 明日のために心身のケア。でも考えるのもめんどくさいあなたへ。
    br
    | 癒しタイムは1日頑張ったあなたに最適な癒しを提案します

.nav.justify-content-center
  = link_to "癒しを設定する", new_treat_path, class: "btn btn-outline-dark me-3"
  = link_to "みんなの履歴", treats_path, class: "btn btn-outline-dark"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TiredTreatment
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
   .app-title.navbar.navbar-expand-md.navbar-light.bg-success 
     .navbar-brand 
      = link_to "癒しタイム", root_path, class: "header-title ms-3 text-warning"
      
   .container 
     -if flash.notice.present?
       .aleert.alert-success= flash.notice
     = yield

app/views/treats/index.html.slim
h1.mt-5 みんなの履歴

.mt-3.mb-3 
  = paginate @treats

table.table.table-hover 
  thead.thead-default 
    tr 
      th= Treat.human_attribute_name(:user)
      th= Treat.human_attribute_name(:event)
      th= Treat.human_attribute_name(:tired_level)
      th= Treat.human_attribute_name(:reward_category)
      th= Treat.human_attribute_name(:reward_name)
  tbody 
    - @treats.each do |treat|
      tr 
        td= treat.user 
        td= treat.event 
        td= treat.tired_level 
        td= treat.reward_category 
        td= treat.reward_name 

.nav.justify-content-center.mb-3 
  = link_to "戻る", root_path, class: "nav-link back-link"

app/views/treats/new.html.slim
h1.mt-5 
  | 出来事の入力
p.text-danger ＊今日のあれこれは必須項目です

- if @treat.errors.present?
  ul#error_explanation.text-danger 
    - @treat.errors.full_messages.each do |message|
      li= message 

= form_with model: @treat, local:true do |f|
  .form-group 
    = f.label :user
    = f.text_field :user, class: "form-control", id: "treat_user", maxlength: 30, autocomplete: "off"
  .form-group 
    = f.label :event, class: "mt-2"
    = f.text_field :event, class: "form-control", id: "treat_event",placeholder: "例)音声オンに気づかなくて、会議中お菓子食べてるのバレた。あーあ。", maxlength: 30, autocomplete: "off"
  .form-group 
    = f.label :tired_level, class: "mt-2"
    = f.select :tired_level, [["1", 1], ["2", 2],["3", 3]], { include_blank: false, selected: 1 }, { class: "form-select", id: "treat_tired_level"}
  .form-group 
    = f.label :reward_category, class: "mt-2"
    = f.select :reward_category, [ ["ごちそう", "ごちそう"], ["ショッピング", "ショッピング"], ["エンタメ", "エンタメ"] ], { include_blank: false, selected: 1 }, { class: "form-select", id: "treat_tired_level"}
  = f.submit "癒しを設定する", class:"btn btn-outline-dark mt-3"

.nav.justify-content-center
  = link_to "戻る", root_path, class: "nav-link back-link"

app/views/treats/show.html.slim
h4.mt-5 
  = "#{@treat.user}さんへのご褒美は..."
h1.text-center 
  = "「#{@treat.reward_name}する」"
h4.text-end 
  | です!

table.table.table-hover 
  tbody 
    tr 
      th= Treat.human_attribute_name(:user)
      td= @treat.user
    tr 
      th= Treat.human_attribute_name(:event)
      td= @treat.event
    tr 
      th= Treat.human_attribute_name(:tired_level)
      td= @treat.tired_level
    tr 
      th= Treat.human_attribute_name(:reward_category)
      td= @treat.reward_category
    tr 
      th= Treat.human_attribute_name(:reward_name)
      td= @treat.reward_name

= link_to "Twitterに投稿する", "http://twitter.com/share?url=#{request.protocol + request.host}/&text=「#{@treat.event}」を達成できたら、#{@treat.reward_name}します！%0a%23癒しタイム%0a", class: "btn btn-outline-primary"

.nav.justify-content-center
  = link_to "戻る", root_path, class: "nav-link back-link"